export const Labels = {
  ACTIVE: "Active",
  ADD_FACE_TO_DATABASE: "Add face to database",
  ADD: "Add",
  BACK_FLOW_LIST: "Back to flow list",
  CLOSE: "Close",
  EDIT_FLOW_NAME: "Edit flow name",
  FACE_ADDED_TO_DB: "Face Added to DB",
  FACE_IN_DATABASE: "Face in database",
  FLOW_NAME: "Flow name",
  FLOW_SAVED_CORRECTLY: "Flow saved correctly.",
  FLOWS: "Flows",
  FULL_NAME_OCR: "Full Name (OCR)",
  GO_TO_IDENTITY: "Go to Identity",
  ID_OCR: "ID OCR",
  IDENTITIES: "Identities",
  IDENTITY_CONFIRMED: "Identity confirmed",
  LIVE_FLOW: "Live flow",
  MENU_ICON: "menu icon",
  NEW_FLOW: "New flow",
  NEW: "New",
  SAVE_CHANGES: "Save Changes",
  SAVE: "Save",
  SEARCH_MODULES: "Search modules",
  SESSION_INFO: "Session info",
  UNSAVED_CHANGES: "Unsaved changes",
};
