export const Labels = {
  ACTIONS: "Actions",
  ACTIVE: "Active",
  ADD_FACE_TO_DATABASE: "Add face to database",
  ADD: "Add",
  CANCEL: "Cancel",
  DETAILS_AND_CONFIGURATION: "Details and configuration",
  EDIT_FLOW_NAME: "Edit flow name",
  FLOW_NAME: "Flow name",
  FLOWS: "Flows",
  FULL_NAME_OCR: "Full Name (OCR)",
  ID_OCR: "ID OCR",
  ID_VERIFICATION: "ID Verification",
  IDENTITIES: "Identities",
  IMPORT: "Import",
  LOG_IN: "Log In",
  MAIN_NAVIGATION: "Main navigation",
  NEW_FLOW: "New flow",
  NEW: "New",
  PASSWORD: "password",
  PRESENTATION: "Presentation",
  REMOVE: "Remove",
  REVIEW_SESSIONS: "Review sessions",
  SAVE_CHANGES: "Save Changes",
  SAVE: "Save",
  SEARCH_MODULES: "Search modules",
  SELECT_MODULES: "Select Modules",
  SESSION_INFO: "Session Info",
  SESSIONS: "Sessions",
  SETTINGS: "Settings",
};
